### ISSUE TITLE
kafka error

### ISSUE THREAD

**Issue by tys-github** [yk-st/pyspark_settings#4]
RUN wget https://dlcdn.apache.org/kafka/3.0.1/kafka_2.13-3.0.2.tgz
でエラーが出ます。
下記の3.0.2にすれば起動しました。
RUN wget https://dlcdn.apache.org/kafka/3.0.2/kafka_2.13-3.0.2.tgz

修正をお願いします。

**Comment by yk-st** [comment]
ご連絡ありがとうございます。
対象部分について修正いたしました。
